### ISSUE TITLE
length of lines, length of words, word count, sentence count (Kimberly)

### ISSUE THREAD

**Issue by HelkeBaeyens** [HelkeBaeyens/read#11]
An important part of level appointment is text structure. The average length of sentences and words can be an indicator in this

**Comment by HelkeBaeyens** [comment]
Ik zou code schrijven voor al dit (dan heb je genoeg code en dit wordt ook zo gedaan in andere readability tools): 

Number of characters (without spaces) : 
Number of words : 	
Number of sentences : 	
Average number of characters per word : 
Average number of syllables per word : 
Average number of words per sentence:
Lexical Density :

**Comment by HelkeBaeyens** [comment]
Conjunctions, komma's

**Comment by kimberly-moors** [comment]
Ja ik heb dit ondertussen al af, aangezien ik klaar was met woordlevel bepaling
