### ISSUE TITLE
word level (Kimberly)

### ISSUE THREAD

**Issue by HelkeBaeyens** [HelkeBaeyens/read#12]
1. Spelling checker build in (optional, aka. When I find out how to work this) = connected to the lemma abstraction
2. Lemma abstraction (see spelling corrector)
Tokenization
Plural, suffixes, verb forms, named entities, bye bye punctuation, grammatical words (linking words), delete numbers, abbr.’s  (+1 hard). 
3. Connecting the word to the correct level 
Outsiders (words not in the program are automatically counted C2)
4. Connecting the text to a word level
To understand a text people need to know at least 90% of a text, therefore I will make the program starting from C2 going downward (less work for the program)

**Comment by kimberly-moors** [comment]
Dit gedeelte is grotendeels af, enkel nog het  spellingchecker gedeelte
