### ISSUE TITLE
Tense determination (Helke)

### ISSUE THREAD

**Issue by HelkeBaeyens** [HelkeBaeyens/read#13]
The program has to be able to recognize the tense and the level that that tense belongs to.
I suppose we can use the same structure as for words . Start from the top by looking to the most difficult structures and then go down.
!!!! take the irregular verbs into account as well!!! I suggest that this person makes an exception list of the irregular verbs with their tenses in each category (this can also be used for the words part but this way this person has more lines.

**Comment by kimberly-moors** [comment]
Since we haven't divided everything already I don't know who is going to do this, but for the irregular verbs it might be useful to take a look at my word_level program. The regexes might be usefull
