### ISSUE TITLE
Sentence level (Kimberly)

### ISSUE THREAD

**Issue by HelkeBaeyens** [HelkeBaeyens/read#16]
Split long sentences on linking words
Make passive sentences active

**Comment by kimberly-moors** [comment]
Hey Helke,
I am almost finished with the sentence splitter and only have to add some coordination/subordination words.
One **question** however: I don't get the new sentences to capitalize. Do you have any ideas? (I tried upper() and lower() in several ways (r'\A'), (sen[0]) and (r^('.') but nothing works.

**Comment by kimberly-moors** [comment]
Not necessary anymore. Solved it.
