### ISSUE TITLE
Machine learning - word level (Helke)

### ISSUE THREAD

**Issue by HelkeBaeyens** [HelkeBaeyens/read#18]
Machine learning: The machine learning tool will predict whether, when simplifying the text, a word will be changed (into which one?) or deleted.
The changes should be highlighted.

**Comment by kimberly-moors** [comment]
Hey Helke, is dit al het volledige gedeelte van machine learning? Want ik denk niet dat ik het goed begrijp. 
Zoals ik het begrijp kijkt ge naar de frequentie van een woord en bepaalt ge a.h.v. deze gegevens of een woord vervangen moet worden. Waar ik dan aan denk. Als een woord B1/A2 niveau is maar weinig voorkomt kleurt het dan ook niet?

**Comment by HelkeBaeyens** [comment]
Hallo Kimberly, er is geen machine learning,want er is geen data...
