### ISSUE TITLE
readme (Helke en Kimberly)

### ISSUE THREAD

**Issue by HelkeBaeyens** [HelkeBaeyens/read#24]
Aanvullen hoe programma werkt (vb met voorbeelden) + hoe de interface best gestart wordt.

**Comment by kimberly-moors** [comment]
Ik dacht er een executable van te maken. Dan heeft de gebruiker zelfs de code niet nodig om het programma te gebruiken. En kan gewoon op het programma klikken. Wat denkt gy?

**Comment by kimberly-moors** [comment]
En hoe het werk: je geeft je input in in de box die zegt geef hier je tekst in. Om je text te analyseren klik je op de knop analyse. Om de text makkelijker te maken klik je op de knop simplify text. 

De overige knoppen zijn voor het openen en opslaan van teksten, het leeg maken van de input box en het afsluiten van het programma.

Mij elk van deze knoppen krijg je een fout melding wanneer je iets fout doet.

**Comment by kimberly-moors** [comment]
Moet ge nog iets van informatie hebben?

**Comment by kimberly-moors** [comment]
Trouwens, is de readme niet hetzelfde als 'abstract, als in: een van de eerste issues? Of ziet gij dit anders?

**Comment by HelkeBaeyens** [comment]
Hej, in de readme staat inderdaad de abstract (en nog vanalles anders). Ik heb het document al klaar gezet, maar je zou ook nog wat moeten toevoegen. Voor die interface klinkt het goed, maar mag ook toegevoegd worden aan de readme.

**Comment by kimberly-moors** [comment]
Readme ziet er heel goed uit. Dictionary file is niet belangrijk voor het gebruik. Moet deze dan ook uitgelegd worden. De uitleg van de interface en het example zal ik morgen uitwerken.
Wat had ge eigenlijk in gedachten kwa voorbeeld?

**Comment by kimberly-moors** [comment]
Hey ik weet niet of je de vraag onder aan mijn vorig bericht gelezen hebt. Wat had ge in gedachten van voorbeeld?
