### ISSUE TITLE
copyright: kijk je de standaard copyright na? Pas wanneer duidelijk is dat onze libraries open source zijn, kan er een open patent aangevraagd worden (dus: nadat we klaar zijn)

### ISSUE THREAD

**Issue by HelkeBaeyens** [HelkeBaeyens/read#25]
# Copyright 2017 Kimberly Moors - Helke Baeyens
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#    1. Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#    2. Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

**Comment by kimberly-moors** [comment]
Klinkt mij wel duidelijk. Moeten we dat op al onze codes zetten of op het project in het algemeen?

**Comment by HelkeBaeyens** [comment]
Moet in apart document. Het staat klaar en ik zal het dan pushen.

**Comment by kimberly-moors** [comment]
Oke XD
