### ISSUE TITLE
word_level: updated, maar kan niets pushen naar jou

### ISSUE THREAD

**Issue by HelkeBaeyens** [HelkeBaeyens/read#26]
Hej Kimberly, ik heb aanpassingen gedaan, maar ik kan niets pushen naar jouw fork. Ik zie dat de readme ook nog niet juist staat.

**Comment by kimberly-moors** [comment]
Ja, da ga ik nog doen. Dat gebeurt wanneer ik een pull request doe.
Ik zou u er wel bewust van willen maken dat het document dat ge hebt aangepast niet de text level bepaler is. Deze zit in de function library.

**Comment by kimberly-moors** [comment]
Hoe gaat het bij u met de tenses?

**Comment by kimberly-moors** [comment]
Maw. ik heb de combining function al geschreven ik moet enkel nog uw functie implementeren.

**Comment by HelkeBaeyens** [comment]
waar staat die? Ik vind die niet? Ik heb een unittest prob met de tenses...

**Comment by kimberly-moors** [comment]
in mijn function_lib onder de functie sentence level: lijnen 93 tot 113

**Comment by HelkeBaeyens** [comment]
Hej, de readme kan ik ook niet pushen... Geef me een seintje wanneer ik rechten heb!

**Comment by kimberly-moors** [comment]
Rechten?

**Comment by kimberly-moors** [comment]
Ik heb gesyncroniseerd.. Kunnen we mss ook effen praten op hangout?
