### ISSUE TITLE
ik kan de interface niet openen omdat hij windows only is (en de proffen hebben mac!)

### ISSUE THREAD

**Issue by HelkeBaeyens** [HelkeBaeyens/read#31]

**Comment by kimberly-moors** [comment]
Huh, gy hebt toch windows?  En de proffen hebben mac maar ik kan geen mac installable maken nog deze uittesten. Wij hebben enkel windowscomputers hier. Trouwens de school computers zijn windows. En we hebben ons examen op school. We kunnen het desnoods op die computers tonen.

Ik dacht dat een installable gewoon een pluspunt zou zijn aan het programma.

**Comment by kimberly-moors** [comment]
Welk computer systeem hebt gy dan?

**Comment by HelkeBaeyens** [comment]
Ik heb een linux. Via wine (windows emulator) kan het geinstalleerd worden, maar draait het niet!

**Comment by kimberly-moors** [comment]
Ah das jammer. En de executable werkt ook niet?
