### ISSUE TITLE
Implementeer problemen

### ISSUE THREAD

**Issue by kimberly-moors** [HelkeBaeyens/read#32]
Hey Helke.  De tense determination heb ik met succes kunnen implementeren. De probability file helaas niet aangezien ik u code niet goed begrijp en zodoende niet weet hoe ik deze kan implementeren.

Je verwijst bij de parameters naar twee soorten files. Waar kan ik deze files vinden? Is hier geen database aan verbonden?

Ik ga nu de installable maken. Als je straks thuiskomt will je hier dan misschien even antwoorden en eventueel meer commentary in je code zetten zodat ik weet wat je bedoelt? Ik zal ahv. je commentaar dan nog proberen aanpassingen te maken in de installable indien mogelijk.

**Comment by HelkeBaeyens** [comment]
Hallo Kimberly, waarvoor zou je die probability gebruiken? Ik heb die eigenlijk geschreven voor het gedeelte moeilijke tekst (van googlescholar) en makkelijke test (gesimplifieerd) te vergelijken en te voorspellen welke woorden aangepast zullen worden.

**Comment by kimberly-moors** [comment]
Ah oke, dus jij berekent de probabiliteit dat een woord vervangen moet worden dmv. de vergelijking van twee teksten. Ik dacht dat er nog een stuk na zou komen dat bepaald waar een tekst moet vereenvoudigd worden (en in een eventueel later stadium ook zou kunnen vervangen) aan de hand van uw berekeningen (ahv. trainingscorpus).  

En zodoende zou kunnen geïmplementeerd worden in de interface.
