### ISSUE TITLE
importance

### ISSUE THREAD

**Issue by HelkeBaeyens** [HelkeBaeyens/read#7]
Kimberly:"We have to decide how important each part of the level indicator is going to be. I suggest tenses and words will have the most weight. But what percentage do we assign to each part?"

**Comment by HelkeBaeyens** [comment]
I propose we check on this in literature

**Comment by kimberly-moors** [comment]
Ik heb deze week al veel nagedacht over de verdeling, en heb gemerkt dat na woordenschat, werkwoordtijden het belangrijkste zijn. 
Ik ben nog aan het nadenken over de details maar zit momenteel met de volgende verdeling: WS = 70%, Tenses = 20% en de overige 10% is lengte van zinnen, co-reference en woordvariatie.
Wat denkt gy?
Tevens zie ik het ook wel zitten om dit gedeelte te programeren
