### ISSUE TITLE
Corpus

### ISSUE THREAD

**Issue by HelkeBaeyens** [HelkeBaeyens/read#8]
Kimberly:"I am still looking for a corpus, but still haven’t found one yet. Therefore, I propose that if I don’t find one today (24/12) we go to plan B (I make one myself based on the texts we have).
In that case I will not help on the trainings set itself since this will take a lot of work(however, to do this I need as many text as possible as soon as possible)"

**Comment by HelkeBaeyens** [comment]
Ik begrijp de vraag niet goed...

**Comment by kimberly-moors** [comment]
Ik bedoel hiermee dat indien ik geen dictionary vond ( wat ik ook niet gedaan heb) ik zelf wel een zou maken (handmatig). In dit geval leek het mij het best als een van ons twee de teksten kiest (en in het EXEL file in data zet, en de andere (hier ben ik al mee bezig) alle woorden afkomstig uit de data zou toevoegen aan de dictionary en de bijbehorende levels opzoeken.
